#!/bin/bash
cd build
rm -f CMakeCache.txt

#cmake -DSPI_BUS_CLOCK_DIVISOR=8 -DADAFRUIT_HX8357D_PITFT=ON -DGPIO_TFT_DATA_CONTROL=25 -DGPIO_TFT_RESET_PIN=17 -DGPIO_TFT_BACKLIGHT=18 -DSINGLE_CORE_BOARD=ON -DARMV6Z=ON -DSTATISTICS=0 -S ..
#cmake -DSPI_BUS_CLOCK_DIVISOR=8 -DADAFRUIT_HX8357D_PITFT=ON -DGPIO_TFT_DATA_CONTROL=25 -DGPIO_TFT_BACKLIGHT=17 -DSINGLE_CORE_BOARD=ON -DARMV6Z=ON -DSTATISTICS=0 -S ..

#cmake -DILI9488=ON -DGPIO_TFT_DATA_CONTROL=25 -DGPIO_TFT_RESET_PIN=1 -DSPI_BUS_CLOCK_DIVISOR=400 -DSTATISTICS=1 -DUSE_DMA_TRANSFERS=OFF -S ..

#cmake -DILI9486L=ON -DGPIO_TFT_DATA_CONTROL=25 -DGPIO_TFT_RESET_PIN=7 -DGPIO_TFT_BACKLIGHT=24 -DSPI_BUS_CLOCK_DIVISOR=14 -DBACKLIGHT_CONTROL=ON ..

#BuyDisplay ili9488
cmake -DILI9486L=ON -DGPIO_TFT_DATA_CONTROL=25 -DGPIO_TFT_RESET_PIN=1 -DSPI_BUS_CLOCK_DIVISOR=12 -DDISPLAY_ROTATE_180_DEGREES=ON -DSTATISTICS=1 ..

#cmake -DILI9486L=ON -DGPIO_TFT_DATA_CONTROL=25 -DGPIO_TFT_RESET_PIN=1 -DSPI_BUS_CLOCK_DIVISOR=14 ..

cd ../

