.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2019 kunzol <marco.schmidt@googlemail.com>,
.\"
.TH Fbcp-ili9341-module 1 "October  5 2019"
.SH NAME
fbcp-ili9341-module \- start and stop fbcp-ili9341
.SH SYNOPSIS
.B fbcp-ili9341-module
.RI (start | stop)
.SH DESCRIPTION
Start or stop 
.B fbcp-ili9341
.PP
.SH OPTIONS
.TP
.B stop
start fbcp-ili9341 including loading module into kernel.
.TP
.B stop
stop fbcp-ili9341 including unloading module from kernel.
